algo/urls.py
from django.urls import path

from . import views

app_name = 'algo'
urlpatterns = [
    path('', views.form_send, name='form_send'),
    path('form_result/', views.form_result, name='form_result'),
    path('table/', views.table, name='table'),
]

atom/urls.py
from django.urls import path

from . import views

app_name = 'atom'
urlpatterns = [
    path('', views.main, name='main'),
    path('service/', views.service, name='service'),
    path('topic/', views.topic, name='topic'),
    path('task/', views.task, name='task'),

]

minor_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('atom.urls')),
    path('algo/', include('algo.urls'))
]

atom/models.py
from django.db import models


# Create your models here.
class ServiceModels(models.Model):
    description = models.CharField(max_length=225)
    name = models.CharField(max_length=225)
    cost = models.IntegerField()
    image = models.CharField(max_length=225)

    def __str__(self):
        return f"{self.id}&{self.name}"

    class Meta:
        verbose_name = "service"
        verbose_name_plural = "services"
        ordering = ('cost',)


class TaskModels(models.Model):
    description = models.CharField(max_length=5000)
    name = models.CharField(max_length=225)

    def __str__(self):
        return f"{self.id}&{self.name}"

    class Meta:
        verbose_name = "task"
        verbose_name_plural = "tasks"
        ordering = ('-id',)


class SolutionModels(models.Model):
    description = models.CharField(max_length=5000)
    name = models.CharField(max_length=225)
    email = models.EmailField(max_length=225)
    current_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}&{self.name}"

    class Meta:
        verbose_name = "solution"
        verbose_name_plural = "solutions"
        ordering = ('-id',)


class UserModels(models.Model):
    surname = models.CharField(max_length=225)
    name = models.CharField(max_length=225)
    phone = models.CharField(max_length=13)
    email = models.EmailField(max_length=225)
    current_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}&{self.surname}"

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"
        ordering = ('id',)


class ScheduleTopicModels(models.Model):
    date = models.CharField(max_length=30)
    title = models.CharField(max_length=225)
    level = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.id}&{self.title}"

    class Meta:
        verbose_name = "topic"
        verbose_name_plural = "topics"
        ordering = ('date', 'level')

atom/views.py
from django.shortcuts import render, redirect
from .models import ServiceModels, TaskModels, SolutionModels
from .models import ScheduleTopicModels, UserModels

# Create your views here.
def main(request):
    if request.method == 'POST':
        surname = request.POST.get('surname')
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        print(surname, name, phone, email)
        if surname and name and phone and email:
            UserModels.objects.create(surname=surname, name=name, phone=phone, email=email)
            return redirect('atom:main')
        else:
            return redirect('atom:main')
    return render(request, 'main.html')


def service(request):
    object = ServiceModels.objects.all()
    print(object)
    context = []
    for i in range(len(object)):
        context.append(object.values('description', 'name', 'cost', 'image')[i])

    return render(request, 'service.html', {'context': context})


def topic(request):

    timetable_data = []

    # Получаем все объекты TimetableModels из базы данных
    timetables = ScheduleTopicModels.objects.all()

    # Создаем словарь, который будет хранить данные расписания для каждого временного слота
    schedule_data = {}

    # Заполняем словарь schedule_data данными из модели TimetableModels
    for timetable in timetables:
        date = timetable.date
        level = timetable.level
        title = timetable.title

        if date not in schedule_data:
            schedule_data[date] = {}

        schedule_data[date][level] = {'title': title}

    # Получаем список временных слотов, отсортированных по времени
    dates = sorted(schedule_data.keys())

    # Получаем список дней недели
    levels = ['1', '2', '3', '4']

    # Создаем список словарей timetable_data для отображения в шаблоне
    for date in dates:
        row_data = {'date': date}

        for level in levels:
            title = schedule_data.get(date, {}).get(level)
            row_data[level.lower() + '_title'] = title

        timetable_data.append(row_data)
    print(timetable_data)
    context = {'timetable_data': timetable_data}
    return render(request, 'topic.html', context)

def task(request):
    if request.method == 'GET':
        task = TaskModels.objects.first()  # Получаем первую задачу из базы данных (вам нужно настроить логику выбора задачи)
        return render(request, 'task.html', {'task': task})
    elif request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        description = request.POST.get('description')
        solution = SolutionModels(name=name, email=email, description=description)
        solution.save()
        return redirect('atom:task')

atom/templates/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Главная</title>
    <link rel="stylesheet" href="../static/main.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'atom:main' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:service' %}">Услуги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:topic' %}">Темы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:task' %}">Задачки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://vk.com/" target="_blank"><img src="../static/vk.png" height="25"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid my-carousel">
    <div id="carouselExampleCaptions" class="carousel carousel-fade" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active image">
                <img src="../static/Qk3rAbjXDQE.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Атом — школа экспериментальной физики. <br>Наши преподаватели – действующие учёные, <br>специалисты
                        технических направлений, <br>кандидаты технических и физико-математических наук.</h5>
                    <div class="text-center mt-4">
                        <a class="btn btn-outline-light" href="#form-section">Записаться</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item image">
                <img src="../static/5rF2v39AcTY.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Атом — школа экспериментальной физики. <br>Наши преподаватели – действующие учёные, <br>специалисты
                        технических направлений, <br>кандидаты технических и физико-математических наук.</h5>
                    <div class="text-center mt-4">
                        <a class="btn btn-outline-light" href="#form-section">Записаться</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item image">
                <img src="../static/Pq-QIIFhKr4.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Атом — школа экспериментальной физики. <br>Наши преподаватели – действующие учёные, <br>специалисты
                        технических направлений, <br>кандидаты технических и физико-математических наук.</h5>
                    <div class="text-center mt-4">
                        <a class="btn btn-outline-light" href="#form-section">Записаться</a>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="row g-4">
                <div class="col-md-6">
                    <img src="../static/image1.jpg" class="img-fluid" alt="Image 1">
                </div>
                <div class="col-md-6">
                    <img src="../static/image2.jpg" class="img-fluid" alt="Image 2">
                </div>
                <div class="col-md-6">
                    <img src="../static/image3.jpg" class="img-fluid" alt="Image 3">
                </div>
                <div class="col-md-6">
                    <img src="../static/image4.jpg" class="img-fluid" alt="Image 4">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h2>Физика через эксперименты детям!</h2>
            <p class="lead">
            <ul>
                АТОМ - это:
                <li>Команда исследователей-физиков</li>
                <li>Море экспериментов и опытов, которые дети могут проделать сами</li>
                <li>4 уровня обучения</li>
                <li>Еженедельные домашние задания</li>
                <li>Итоговые контрольные работы и проект в конце</li>
            </ul>
            </p>
        </div>
    </div>
</div>


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-sm-4 text-center">
            <h3>Запись в кружок по экспериментальной физике АТОМ</h3>
            <form action="{% url 'atom:main' %}" id="form-section" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="surname" class="form-label"></label>
                    <input type="text" name="surname" class="form-control" id="surname" required placeholder="Фамилия">
                </div>
                <div class="mb-3">
                    <label for="name" class="form-label"></label>
                    <input type="text" name="name" class="form-control" id="name" required placeholder="Имя">
                </div>
                <div class="mb-3">
                    <label for="emailAddress" class="form-label"></label>
                    <input type="email" name="email" class="form-control" id="emailAdress" required placeholder="Email">
                </div>
                <div class="mb-3">
                    <label for="number" class="form-label"></label>
                    <input type="tel" name="phone" class="form-control" id="phoneNumber" required placeholder="Телефон">
                </div>
                <button type="submit" class="btn btn-outline-dark">Отправить</button>
            </form>
        </div>
    </div>
</div>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        </a>
        <span class="mb-3 mb-md-0 text-muted">© 2023 Company, Inc</span>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

atom/templates/service.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Главная</title>
    <link rel="stylesheet" href="../static/main.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:main' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'atom:service' %}">Услуги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:topic' %}">Темы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:task' %}">Задачки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://vk.com/" target="_blank"><img src="../static/vk.png" height="25"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container mt-4">
    <div class="row row-cols-2 g-4">
        {% for item in context %}
        <div class="col">
            <div class="card h-100">
                <img src="../static/{{ item.image }}" class="card-img-top w-100 h-100" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ item.name }}</h5>
                    <p class="card-text">{{ item.description }}</p>
                    <p class="card-text">{{ item.cost }} р.</p>
                    <button onclick="window.location.href = '{% url 'atom:main' %}#form-section'" type="button" class="btn btn-outline-dark">Записаться</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>





<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        </a>
        <span class="mb-3 mb-md-0 text-muted">© 2023 Company, Inc</span>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

atom/templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Задачи</title>
    <link rel="stylesheet" href="../static/main.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:main' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:service' %}">Услуги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:topic' %}">Темы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'atom:task' %}">Задачки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://vk.com/" target="_blank"><img src="../static/vk.png" height="25"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container mt-5">
    <h1 class="display-5">{{ task.name }}</h1>
    <h1 class="display-6">{{ task.description }}</h1>
</div>

<div class="container mt-5">
    <form method="POST" action="{% url 'atom:task' %}">
        {% csrf_token %}
        <p class="lead">Отправьте нам свое решение, если хотите получить обратную связь</p>
        <input type="hidden" name="task_id" value="{{ task.id }}">
        <div class="mb-3">
            <label for="solutionName"></label>
            <input type="text" class="form-control" id="solutionName" name="name" required placeholder="ФИО">
        </div>
        <div class="mb-3">
            <label for="solutionEmail"></label>
            <input type="email" class="form-control" id="solutionEmail" name="email" required placeholder="Email">
        </div>
        <div class="mb-3">
            <label for="solutionDescription"></label>
            <textarea class="form-control" id="solutionDescription" name="description" rows="5" required
                      placeholder="Решение"></textarea>
        </div>
        <button type="submit" class="btn btn-outline-dark">Отправить</button>
    </form>
</div>

<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        </a>
        <span class="mb-3 mb-md-0 text-muted">© 2023 Company, Inc</span>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

atom/templates/topic.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Главная</title>
    <link rel="stylesheet" href="../static/main.css">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:main' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:service' %}">Услуги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'atom:topic' %}">Темы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atom:task' %}">Задачки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://vk.com/" target="_blank"><img src="../static/vk.png" height="25"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container mt-4">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col"> <a href="https://calendar.google.com/calendar/u/0/r">Дата</a></th>
            <th scope="col">Уровень
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-1-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2Zm7.283 4.002V12H7.971V5.338h-.065L6.072 6.656V5.385l1.899-1.383h1.312Z"/>
                </svg>
            </th>
            <th scope="col">Уровень
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-2-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2Zm4.646 6.24v.07H5.375v-.064c0-1.213.879-2.402 2.637-2.402 1.582 0 2.613.949 2.613 2.215 0 1.002-.6 1.667-1.287 2.43l-.096.107-1.974 2.22v.077h3.498V12H5.422v-.832l2.97-3.293c.434-.475.903-1.008.903-1.705 0-.744-.557-1.236-1.313-1.236-.843 0-1.336.615-1.336 1.306Z"/>
                </svg>
            </th>
            <th scope="col">Уровень
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-3-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2Zm5.918 8.414h-.879V7.342h.838c.78 0 1.348-.522 1.342-1.237 0-.709-.563-1.195-1.348-1.195-.79 0-1.312.498-1.348 1.055H5.275c.036-1.137.95-2.115 2.625-2.121 1.594-.012 2.608.885 2.637 2.062.023 1.137-.885 1.776-1.482 1.875v.07c.703.07 1.71.64 1.734 1.917.024 1.459-1.277 2.396-2.93 2.396-1.705 0-2.707-.967-2.754-2.144H6.33c.059.597.68 1.06 1.541 1.066.973.006 1.6-.563 1.588-1.354-.006-.779-.621-1.318-1.541-1.318Z"/>
                </svg>
            </th>
            <th scope="col">Уровень
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-4-square-fill" viewBox="0 0 16 16">
                    <path d="M6.225 9.281v.053H8.85V5.063h-.065c-.867 1.33-1.787 2.806-2.56 4.218Z"/>
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2Zm5.519 5.057c.22-.352.439-.703.657-1.055h1.933v5.332h1.008v1.107H10.11V12H8.85v-1.559H4.978V9.322c.77-1.427 1.656-2.847 2.542-4.265Z"/>
                </svg>
            </th>
        </tr>
        </thead>
        <tbody>
        {% for slot in timetable_data %}
            <tr>
                <td>{{ slot.date }}</td>
                <td>
                    {{ slot.1_title.title }}<br>
                </td>
                <td>
                    {{ slot.2_title.title }}<br>
                </td>
                <td>
                    {{ slot.3_title.title }}<br>
                </td>
                <td>
                    {{ slot.4_title.title }}<br>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        </a>
        <span class="mb-3 mb-md-0 text-muted">© 2023 Кружок по физике Атом</span>
    </div>
</footer>
</body>